spring:
  datasource:
    url: jdbc:h2:mem:bci
    driverClassName: org.h2.Driver
    username: martin
    password: martin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
key:
  jwt-secret: JWTSecretKey
  jwt-expiration: 714856842
server:
  error:
    include-message: always
    include-binding-errors: always